### ISSUE TITLE
StatusBarColor No Changed?

### ISSUE THREAD

**Issue by BadDeveloper2022** [yageek/StickyHeader#1]
![image](https://cloud.githubusercontent.com/assets/7404699/23247066/d8343ba8-f9d2-11e6-8212-bc0607d6ce5c.png)

**Comment by BadDeveloper2022** [comment]
let frame = CGRect(x: 0, y: relativeYOffset-20, width: scrollView.frame.size.width, height: height)

**Comment by BadDeveloper2022** [comment]
![image](https://cloud.githubusercontent.com/assets/7404699/23247424/f1dd21b2-f9d4-11e6-8122-12a9f488eedb.png)

**Comment by yageek** [comment]
Could you provide some more context? I do not understand if the issue is related to the color of the status bar or its position or both?
